name: Build with Emscripten

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v11
        with:
          # Make sure to set a version number!
          version: 3.1.38
          # This is the name of the cache folder.
          # The cache folder will be placed in the build directory,
          #  so make sure it doesn't conflict with anything!
          actions-cache-folder: 'emsdk-cache'

      - name: Verify
        run: emcc -v

      - name: Install dependencies
        run: |
          # Install required dependencies
          sudo apt-get update
          sudo apt-get install -y build-essential libboost-graph-dev nasm bison flex texinfo zlib1g-dev

      - name: Init submodules
        run: |
          # Initialize and update Git submodules
          git submodule init
          git submodule update

  cc65:
    needs: setup
    steps:
      - name: Build CC65
        run: make cc65

  sdcc:
    needs: setup
    steps:
      - name: Build SDCC
        run: make sdcc

  tools6809:
    needs: setup
    steps:
      - name: Build 6809tools
        run: make 6809tools

  verilator:
    needs: setup
    steps:
      - name: Build verilator
        run: make verilator

  zmac:
    needs: setup
    steps:
      - name: Build zmac
        run: make zmac

  merlin32:
    needs: setup
    steps:
      - name: Build merlin32
        run: make merlin32

  c2t:
    needs: setup
    steps:
      - name: Build c2t
        run: make c2t

  makewav:
    needs: setup
    steps:
      - name: Build makewav
        run: make makewav

  dasm:
    needs: setup
    steps:
      - name: Build dasm
        run: make dasm

  wiz:
    needs: setup
    steps:
      - name: Build wiz
        run: make wiz

  fastbasic:
    needs: setup
    steps:
      - name: Build fastbasic
        run: make fastbasic

#      - name: Move output files
#        run: cp -rp output/ ${{ github.workspace }}/output/
